esphome:
  name: dongle01

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

safe_mode:
  boot_is_good_after: 
    minutes: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - switch.turn_on: led_wifi
  on_disconnect:
    then:
      - switch.turn_off: led_wifi

uart:
  id: rs485_uart
  tx_pin: GPIO17
  rx_pin: GPIO4
  baud_rate: 19200
  parity: NONE
  data_bits: 8
  stop_bits: 1
  debug:
    dummy_receiver: false
    after:
      delimiter: "\r\n"

modbus:
  id: modbus1
  uart_id: rs485_uart
  flow_control_pin:
    number: GPIO32
    inverted: true

modbus_controller:
  - id: modbus_conroller1
    address: 1
    modbus_id: modbus1
    update_interval: 15s

# NOTE: either wifi or ethernet can be enabled, not both
#
# ethernet:
#   type: IP101
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   power_pin: GPIO5
#   phy_addr: 1
#   clk:
#     pin: GPIO0
#     mode: CLK_OUT

switch:
  - platform: gpio
    id: led_wifi
    internal: True
    name: Wifi LED
    pin:
      number: GPIO15
      ignore_strapping_warning: True
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: led_inv
    name: INV LED
    internal: True
    pin:
      number: GPIO33
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_ON

  - platform: gpio
    id: led_cloud
    name: Cloud LED
    internal: True
    pin:
      number: GPIO13
      mode: OUTPUT
      inverted: True
    restore_mode: ALWAYS_OFF
