esphome:
  name: dongle01

esp32:
  board: esp32dev
  framework:
    type: esp-idf


uart:
  id: rs485_uart
  tx_pin: GPIO17
  rx_pin: GPIO4
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

modbus:
  id: mb
  uart_id: rs485_uart
  flow_control_pin:
    number: GPIO32
    inverted: true

modbus_controller:
  - id: inverter_1
    address: 1
    modbus_id: mb
    update_interval: 60s

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO5
  phy_addr: 1
  clk:
    pin: GPIO0
    mode: CLK_OUT

switch:
  - platform: gpio
    name: "LED13 Forced"
    pin:
      number: GPIO13
      mode: OUTPUT
    restore_mode: ALWAYS_OFF
